/* DELETE */

/* BE CAREFUL WITH THESE STATEMENTS --> NO RETURN */

/* DELETE THE DATE'S INFORMATIONS */

DELETE FROM booking_date
WHERE date_id_pk = '';

/* DELETE A CUSTOMER /*
/* -> SHOULD NOT BE NEEDED BUT A CUSTOMER COULD WANT TO ERASE THE INFORMATIONS ABOUT HIM */

DELETE FROM customer
WHERE customer_id_pk = '';


/* DELETE A MEAL  / CANCEL  (ONLY ONE MEAL) */

DELETE FROM meal
WHERE meal_id_pk = '';


/* DELETE ALL THE MEALS OF A BOOKING */

DELETE FROM meal
WHERE booking_id_fk = '';


/* DELETE A RECORD IN THE BOOKING'S ENTITY */
/* LAST STATEMENT IF WE WANT TO ERASE ALL THE INFORMATIONS REGARDING A BOOKING */

DELETE FROM booking
WHERE booking_id_pk = '';