/* UPDATE NUMBER OF PERSONS IN ENTITY BOOKING (TOTAL NUMBER OF PERSON) */
/* FIRST STEP */

UPDATE booking
SET b_nb_person = ''

WHERE booking_id_pk = '';

/* AFTER THIS IT MIGHT BE MANDATORY TO CHANGE THE NUMBER OF TABLES USED BY THIS BOOKING */
/* SEE FILES 
    -> ADD NEW TABLE
    -> DELETE A TABLE
    -> UPDATE_NB_PERSON_TABLE (WHEN THE NUMBER OF TABLES DOESN'T CHANGE)
/*